#include <stdlib.h>
#include <stdio.h>

const char* CharacterList[] = {
    "Serge",
    "Kid",
    "Guile",
    "Norris",
    "Nikki",
    "Viper",
    "Riddel",
    "Karsh",
    "Zoah",
    "Marcy",
    "Korcha",
    "Luccia",
    "Poshul",
    "Razzly",
    "Zappa",
    "Orcha",
    "Radius",
    "Fargo",
    "Macha",
    "Glenn",
    "Leena",
    "Miki",
    "Harle",
    "Janice",
    "Draggy",
    "Starky",
    "Sprigg",
    "Mojo",
    "Turnip",
    "NeoFio",
    "Greco",
    "Skelly",
    "Funguy",
    "Irenes",
    "Mel",
    "Leah",
    "Van",
    "Sneff",
    "Steena",
    "Doc",
    "Grobyc",
    "Pierre",
    "Orlha",
    "Pip",
    "Pip",
    "Pip",
    "Pip",
    "Pip",
    "Pip"
};

const char* GetCharacterName(unsigned int idx)
{
    if(idx < (sizeof(CharacterList) / sizeof(const char*)))
        return CharacterList[idx];
    return NULL;
}

const char* ElementList[] = {
    "dummy",
    "AquaBeam",
    "AquaBall",
    "Deluge",
    "IceLance",
    "IceBlast",
    "Iceberg",
    "Fireball",
    "FirePillar",
    "Inferno",
    "MagmaBomb",
    "MagmaBurst",
    "Volcano",
    "Bushwhacker",
    "Bushbasher",
    "Carnivore",
    "AeroSaucer",
    "AeroBlaster",
    "Tornado",
    "Uplift",
    "Upheaval",
    "Earthquake",
    "ElectroJolt",
    "ElectroBolt",
    "ThundaStorm",
    "PhotonRay",
    "PhotonBeam",
    "HolyLight",
    "Meteorite",
    "MeteorShower",
    "UltraNova",
    "GravityBlow",
    "Gravitonne",
    "FreeFall",
    "HellSoul",
    "HellBound",
    "BlackHole",
    "(Summon)FrogPrince",
    "(Summon)BlueWhale",
    "(Summon)RedWolf",
    "(Summon)Salamander",
    "(Summon)Sonja",
    "(Summon)Genie",
    "(Summon)Golem",
    "(Summon)ThundaSnake",
    "(Summon)Unicorn",
    "(Summon)Saints",
    "(Summon)MotherShip",
    "(Summon)GrimReaper",
    "TurnBlue",
    "AntiRed",
    "Nimble",
    "Numble",
    "BlueField",
    "Vigora",
    "TurnRed",
    "AntiBlue",
    "Strengthen",
    "Weaken",
    "RedField",
    "Ninety-Nine",
    "TurnGreen",
    "AntiYellow",
    "EagleEye",
    "BatEye",
    "GreenField",
    "InfoScope",
    "TurnYellow",
    "AntiGreen",
    "HiRes",
    "LoRes",
    "YellowField",
    "PhysNegate",
    "TurnWhite",
    "AntiBlack",
    "StrongMinded",
    "WeakMinded",
    "Magnify",
    "MagNegate",
    "TurnBlack",
    "AntiWhite",
    "Genius",
    "Imbecile",
    "Diminish",
    "SealAll",
    "Cure",
    "CurePlus",
    "CureAll",
    "Heal",
    "HealAll",
    "HealPlus",
    "Purify",
    "RecoverAll",
    "HolyHealing",
    "Revive",
    "FullRevival",
    "Revenge",
    "(Object)Medicine",
    "(Object)Ointment",
    "(Object)Recharge",
    "(Object)Antidote",
    "(Object)Brace",
    "(Object)WhiteOut",
    "(Object)Panacea",
    "(Object)BlackOut",
    "(Object)Tablet",
    "(Object)Capsule",
    "(Object)Nostrum",
    "(Trap)Inferno",
    "(Trap)Volcano",
    "(Trap)RedWolf",
    "(Trap)Deluge",
    "(Trap)Iceberg",
    "(Trap)FrogPrince",
    "(Trap)Earthquake",
    "(Trap)ThundaStorm",
    "(Trap)Golem",
    "(Trap)Carnivore",
    "(Trap)Tornado",
    "(Trap)Sonja",
    "(Trap)FreeFall",
    "(Trap)BlackHole",
    "(Trap)MotherShip",
    "(Trap)HolyLight",
    "(Trap)UltraNova",
    "(Trap)Unicorn",
    "ChronoCross",
    "EL_127",
    "EL_128",
    "EL_129",
    "EL_130",
    "EL_131",
    "EL_132",
    "EL_133",
    "EL_134",
    "EL_135",
    "(Tech)Z-Slash",
    "(Tech)DeltaForce",
    "(Tech)DraggyRider",
    "(Tech)VitalForce",
    "(Tech)TossedSalad",
    "(Tech)Flamenco",
    "(Tech)DoubleTake",
    "(Tech)PitchBlack",
    "(Tech)SwordStorm",
    "(Tech)DragonSpike",
    "(Tech)WindSlash",
    "(Tech)DashSlash",
    "(Tech)TheStare",
    "(Tech)MaxDefense",
    "(Tech)GlideHook",
    "(Tech)FeralCats",
    "(Tech)ForeverZero",
    "(Tech)Dash&Slash",
    "(Tech)SonicSword",
    "(Tech)Dive&Drive",
    "(Tech)GlideHook",
    "(Tech)FeralCats",
    "(Tech)ForeverZero",
    "(Tech)X-Strike",
    "(Tech)Dash&Slash",
    "(Tech)Luminaire",
    "(Tech)FlyingArrow",
    "(Tech)Pilfer",
    "(Tech)RedPin",
    "(Tech)HotShot",
    "(Tech)WandaIn",
    "(Tech)WandaSwords",
    "(Tech)LightninRod",
    "(Tech)SpiralRay",
    "(Tech)SunShower",
    "(Tech)TopShot",
    "(Tech)GrandFinale",
    "(Tech)ChillOut",
    "(Tech)LimeLight",
    "(Tech)G-Force",
    "(Tech)AirForce",
    "(Tech)FlagBearer",
    "(Tech)SnakeEyes",
    "(Tech)SnakeSkin",
    "(Tech)SnakeFangs",
    "(Tech)DragonRider",
    "(Tech)AxialAxe",
    "(Tech)Axiomatic",
    "(Tech)DragonRider",
    "(Tech)Gyronimo",
    "(Tech)Toss&Spike",
    "(Tech)Cat'sCradle",
    "(Tech)StringPhone",
    "(Tech)WebSurfer",
    "(Tech)HeadButt",
    "(Tech)Hook&Sinker",
    "(Tech)BigCatch",
    "(Tech)Pin-UpGirl",
    "(Tech)Mix&Match",
    "(Tech)TestAmeba",
    "(Tech)K9-Ball",
    "(Tech)DoggyDunnit",
    "(Tech)Unleashed",
    "-Star",
    "-Heart",
    "-Flower",
    "(Tech)HammerBlow",
    "(Tech)HammerThrow",
    "(Tech)BallsOfIron",
    "(Tech)SpiceOfLife",
    "(Tech)MysteryMenu",
    "(Tech)DinnerGuest",
    "(Tech)LongShot",
    "(Tech)QuickDraw",
    "(Tech)VitalEnergy",
    "(Tech)Pillage",
    "(Tech)CannonBalls",
    "(Tech)Invincible",
    "(Tech)BottomsUp",
    "(Tech)Folding",
    "(Tech)DirtyDishes",
    "(Tech)Dash&Gash",
    "(Tech)SonicSword",
    "(Tech)Dive&Drive",
    "(Tech)MaidenHand",
    "(Tech)MaidenHeart",
    "(Tech)MaidenFaith",
    "(Tech)HeadBopper",
    "(Tech)SexyWink",
    "(Tech)DanceOnAir",
    "(Tech)MoonBeams",
    "(Tech)MoonShine",
    "(Tech)Lunairetic",
    "(Tech)BeatIt",
    "(Tech)24Carrots",
    "(Tech)What'sUpDoc",
    "(Tech)CoughDrop",
    "(Tech)CoughMix",
    "(Tech)BigBreath",
    "(Tech)StarLight",
    "(Tech)StarBurst",
    "(Tech)StarStruck",
    "(Tech)Doppelgang",
    "(Tech)VoodooDance",
    "(Tech)CartWheel",
    "(Tech)HoodooGuroo",
    "(Tech)VegeChopper",
    "(Tech)VegeMight",
    "(Tech)VegOut",
    "(Tech)PopPopPop",
    "(Tech)SlurpSlurp",
    "(Tech)BamBamBam",
    "(Tech)Clothesline",
    "(Tech)Flip-flop",
    "(Tech)GraveDigger",
    "(Tech)JugglerVein",
    "(Tech)BalloonLoan",
    "(Tech)OnARoll",
    "(Tech)LumberJack",
    "(Tech)SporeCloud",
    "(Tech)Myconoids",
    "(Tech)WaterBreath",
    "(Tech)MerMelody",
    "(Tech)SirenSong",
    "(Tech)Snatch",
    "(Tech)Doodle",
    "(Tech)Tantrum",
    "(Tech)RockThrow",
    "(Tech)TailSpin",
    "(Tech)TripleKick",
    "(Tech)JumpThrow",
    "(Tech)WetPaint",
    "(Tech)PiggyBoink",
    "(Tech)BigDeal",
    "(Tech)HPShuffle",
    "(Tech)SwordTrick",
    "(Tech)DireaShadow",
    "(Tech)HydraShadow",
    "(Tech)GaraiShadow",
    "(Tech)HighFive",
    "(Tech)Gnarly",
    "(Tech)HangTen",
    "(Tech)RocketFist ",
    "(Tech)HairCutter",
    "(Tech)StrongArm",
    "(Tech)Medalsome",
    "(Tech)FoiledAgain",
    "(Tech)SlapOfCyrus",
    "(Tech)Multipunch",
    "(Tech)PunchDrunk",
    "(Tech)SisterHoods",
    "(Tech)Pounce",
    "(Tech)Soothe",
    "(Tech)Pounce",
    "(Tech)Soothe",
    "(Tech)Pounce",
    "(Tech)Soothe",
    "(Tech)Pounce",
    "(Tech)Soothe",
    "(Tech)Hell'sFury",
    "(Tech)Pounce",
    "(Tech)Soothe",
    "(Tech)CanonCannon",
    "(Tech)Pounce",
    "(Tech)Soothe",
    "(Tech)HeavenCalls",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    "(Tech)Lunge",
    " ",
    " ",
    " ",
    "(Tech)PutridOdor",
    "(Tech)NeedleWork",
    " ",
    " ",
    " ",
    "(Tech)VaryInnate",
    " ",
    " ",
    "(Tech)OwlEyes",
    " ",
    " ",
    "(Tech)GunnerGetya",
    " ",
    "(Tech)GoBallistic",
    "(Tech)Dash&Slash",
    "(Tech)Plasmabeam",
    "(Tech)Plasmabeam",
    "(Tech)SuicideBomb",
    " ",
    "(Tech)Deluge",
    "(Tech)DarkBeam",
    "(Tech)SquirtGun",
    "(Tech)Brimstone",
    "(Tech)SuckBlood",
    "(Tech)Hypnosis",
    "(Tech)StepDown",
    "(Tech)PaperMoon",
    "(Tech)Slots",
    " ",
    "(Summon)Golem",
    "(Tech)BeatenEarth",
    "(Tech)Surf'sUp",
    "(Tech)MakeWaves",
    "(Tech)Breath",
    "(Tech)Summersolt",
    "(Tech)Pepporbox",
    "(Tech)CrossCut",
    "(Tech)Bite",
    "(Tech)Sic'em",
    "(Tech)Peck",
    "(Tech)TheOld1-2-3",
    "(Tech)Devour",
    "(Tech)TwinTurbo",
    "(Tech)IceSword",
    "(Tech)FlameSword",
    "(Tech)StormBlow",
    "(Tech)AcaciaBlade",
    "(Tech)FlameKnock",
    " ",
    " ",
    " ",
    "(Tech)Shadow",
    "(Tech)Hi-HoWarCry",
    "(Tech)HighBeam",
    "(Tech)MegatonFist",
    "(Tech)Hi-HoChorus",
    "(Tech)ToxicBurst",
    "(Tech)Wallop",
    " ",
    "(Tech)Hexahitter",
    "(Tech)Whop",
    "(Tech)SwordDance",
    " ",
    "(Tech)Death'sOdor",
    "(Tech)Repair",
    "(Tech)GnawBones",
    "(Tech)TripleFist",
    "(Tech)LavaBreath",
    "(Tech)LavaRush",
    "(Tech)FieryBreath",
    "(Tech)BatBeam",
    "(Tech)Gnash",
    "(Tech)Kissy-Wissy",
    "(Tech)ModeChange",
    "(Tech)TakeIn",
    "(Tech)ChokeSlam",
    "(Tech)BackDrop",
    "(Tech)BodyPress",
    "(Tech)Acac.Breath",
    "(Tech)Lunge",
    " ",
    "(Tech)DevilThunda",
    "(Tech)GlideHook",
    " ",
    "(Tech)BayonetGun",
    "(Tech)BayonetPlus",
    "(Tech)DarkBreath",
    "(Tech)Downpour",
    " ",
    " ",
    "(Tech)TripleCut",
    "(Tech)WillBreaker",
    " ",
    "(Tech)Rampage",
    "(Tech)ExhaustGas",
    "(Tech)AttackAll",
    "(Tech)DeathSaucer",
    "(Tech)IceTongs",
    "(Tech)BugKamikaze",
    "(Tech)JitterBug",
    "(Tech)ColdBreath",
    "(Tech)HotEdge",
    "(Tech)SpinOff",
    "(Tech)BombsAway",
    "(Tech)NaturalGas",
    "(Tech)Catastrophe",
    "(Tech)Just4Kicks",
    "(Tech)FlyLow",
    "(Tech)JumpStart",
    "(Tech)Devour",
    "(Tech)TsunamiBeam",
    "(Tech)IceBreath",
    "(Tech)GravityBomb",
    "(Tech)Charge!",
    "(Tech)FireBreath",
    " ",
    "(Tech)Stinger",
    "(Tech)BugSwatter",
    "(Tech)JurasicBeat",
    "(Tech)CrunchOut",
    "(Tech)Flap",
    " ",
    "(Tech)BadBreath",
    "(Tech)Raydiation",
    "(Tech)HolyBreath",
    "(Tech)DarkEnergy",
    "(Tech)HeatRay",
    "(Tech)Vortex",
    "(Tech)Slime",
    "(Tech)Multistab",
    "(Tech)Dash&Gash",
    "(Tech)SonicSword",
    "(Tech)ConductaRod",
    "(Tech)GiddyBreath",
    "(Tech)BodySlam",
    "(Tech)SplitNuclei",
    "(Tech)SlashAll",
    "(Tech)PowerDive",
    "(Tech)HeartColor",
    "(Tech)PeaShooter",
    "(Tech)BrightEyes",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    "(Tech)HolyDragSwd",
    "(Tech)BoneNeedles",
    "(Tech)OmegaGreen",
    "(Tech)OmegaWhite",
    "(Tech)OmegaBlack",
    "(Tech)OmegaRed",
    "(Tech)OmegaYellow",
    "(Tech)OmegaBlue",
    "(Tech)Rage",
    "(Tech)SadnessWave",
    "(Tech)SpiritsUp",
    "(Tech)WaveOfFear",
    "(Tech)NullState",
    "(Tech)CrashPulse",
    "(Tech)ToxicBreath",
    "(Tech)WhiteBreath",
    "(Tech)DarkBreath",
    "(Tech)FireBreath",
    "(Tech)GiddyBreath",
    "(Tech)AcidicGas",
    "(Tech)ElementShot",
    "(Tech)ElementShot",
    "(Tech)ElementShot",
    "(Tech)ElementShot",
    "(Tech)ElementShot",
    "(Tech)ElementShot",
    "(Tech)PoisonGas",
    "(Tech)DarkMist",
    "(Tech)BlackRain",
    "(Tech)Goo",
    "(Tech)GooeyGoo",
    "(Tech)Bazooka",
    "(Tech)NeedleWork",
    "(Trap)????",
};

const char* CommonItemList[] = {
    " ",
    "(Mat)Bone",
    "(Mat)Copper",
    "(Mat)Iron",
    "(Mat)Mythril",
    "(Mat)Denadorite",
    "(Mat)Rainbow Shell",
    "(Mat)Eyeball",
    "(Mat)Humour",
    "(Mat)Feather",
    "(Mat)Scale",
    "(Mat)Fur",
    "(Mat)Leather",
    "(Mat)Fang",
    "(Mat)Carapace",
    "(Mat)Screw",
    "(Mat)Seed",
    "(Mat)Shiny Ember",
    "(Mat)Shiny Dew",
    "(Mat)Shiny Leaf",
    "(Mat)Shiny Sand",
    "(Mat)Shiny Salt",
    "(Mat)Shiny Soot",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    "Sea Swallow",
    "Copper Swallow",
    "Steel Swallow",
    "Silver Swallow",
    "Stone Swallow",
    "Spectra Swallow",
    "Mastermune",
    "Ivory Dagger",
    "Bronze Dagger",
    "Iron Dagger",
    "Mythril Dagger",
    "Denadorite Dagger",
    "Prism Dagger",
    "Silver Staff",
    "Stone Staff",
    "Spectral Staff",
    "Porcelain Rod",
    "Brass Rod",
    "Iron Rod",
    "Mythril Rod",
    "Denadorite Rod",
    "Rainbow Rod",
    "Floral Rod",
    "Bone Sword",
    "Bronze Sword",
    "Steel Sword",
    "Silver Sword",
    "Stone Sword",
    "Spectral Sword",
    "Hero's Blade",
    "Viper's Venom",
    "Einlanzer",
    "Einlanzer",
    "Slasher",
    "Ferrous Gun",
    "Argent Gun",
    "Denadorite Gun",
    "Spectral Gun",
    "Shockwave Gun",
    "Plasma Pistol",
    "Porcelain Pick",
    "Brass Pick",
    "Iron Pick",
    "Mythril Pick",
    "Pebble Pick",
    "Prism Pick",
    "Carrot",
    "Betta Carotene",
    "Bone Axe",
    "Bronze Axe",
    "Iron Axe",
    "Silver Axe",
    "Stone Axe",
    "Rainbow Axe",
    " ",
    "Great Hammer",
    "Master Hammer",
    "Bronze Lure",
    "Iron Lure",
    "Mythril Lure",
    "Stone Lure",
    "Prism Lure",
    " ",
    "Bronzerang",
    "Steelerang",
    "Silverang",
    "Rockerang",
    "Prismarang",
    " ",
    "Bone Shot",
    "Bronze Shot",
    "Steel Shot",
    "Silver Shot",
    "Stone Shot",
    "Prism Pellets",
    "Private Deck",
    "Pack of Lies",
    " ",
    "Spatula Ca20",
    "Besom Cu29",
    "Ladle Fe26",
    "Frypan Ag47",
    "Saucepan SiO2",
    "Crystalpan C6",
    " ",
    "Bone Glove",
    "Bronze Glove",
    "Iron Glove",
    "Mythril Glove",
    "Granite Glove",
    "Spectral Glove",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    "Ivory Mail",
    "Bronze Mail",
    "Iron Mail",
    "Mythril Mail",
    "Stone Mail",
    "Prism Mail",
    "Ivory Vest",
    "Bronze Vest",
    "Iron Vest",
    "Mythril Vest",
    "Stone Vest",
    "Prism Vest",
    "Blue Plate",
    "Red Plate",
    "Yellow Plate",
    "Green Plate",
    "Black Plate",
    "White Plate",
    "Feathery Dress",
    "Scaley Dress",
    "Carapace Dress",
    "Screwy Dress",
    "Diva Dress",
    "Wisp Cape",
    "Cloud Cape",
    "Stardust Cape",
    "Energizer Suit",
    "Ghetz's Shirt",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    "Ozzie Pants",
    "Flea Vest",
    "Antitoxinal Cap",
    "Poultice Cap",
    "Plaster Cap",
    "Antiviral Cap",
    "Hero's Medal",
    "Hero's Shield",
    "Ivory Helmet",
    "Bronze Helmet",
    "Iron Helmet",
    "Mythril Helmet",
    "Stone Helmet",
    "Prism Helmet",
    "Power Glove",
    "Dragoon Gauntlet",
    "Power Seal",
    "Magic Ring",
    "Sky Djinn Ring",
    "Magic Seal",
    "Silver Loupe",
    "Sight Scope",
    "Third Eye",
    "Knee Pad",
    "Elbow Pad",
    "Waist Pad",
    "Silver Pendant",
    "Gold Pendant",
    "Memento Pendant",
    "Dancing Shoes",
    "Kung-fu Shoes",
    "Winged Shoes",
    "Dragoon's Honor",
    "Dragoon's Glory",
    "Defender",
    "Defender Plus",
    "Silver Earring",
    "Gold Earring",
    "Earring of Light",
    "Earring of Hope",
    "Stamina Ring",
    "Stamina Belt",
    "Resistance Ring",
    "Resistance Belt",
    "Sea Charm",
    "Flame Charm",
    "Forest Charm",
    "Earth Charm",
    "Angel Charm",
    "Daemon Charm",
    "Blue Brooch",
    "Red Brooch",
    "Green Brooch",
    "Yellow Brooch",
    "White Brooch",
    "Black Brooch",
    "Dreamer's Scarf",
    "Dreamer's Sash",
    "Trashy Tiara",
    "Golden Tiara",
    "Profiteer Purse",
    "Moonglasses",
    "Sunglasses",
    "Pendragon Sigil C",
    "Pendragon Sigil B",
    "Pendragon Sigil A",
    "Forget-me-not Pot",
    "Star Fragment",
    "Dreamer's Sarong",
    " "
};

const char* RareItemList[] = {
    "                ",
    "Tele-Porter",
    "Shark Tooth",
    "Astral Amulet",
    "Green Tinkler",
    "Beeba Flute",
    "Einlanzer",
    "Ice Gun",
    "Ice Breath",
    "Heckran Bone",
    "Bellflower",
    "Big Egg",
    "Heavy Skull",
    "Good Backbone",
    "Sturdy Ribs",
    "Pelvic Bone",
    "Angry Scapula",
    "Mixed Bones",
    "Aroma Pouch",
    "Mushroom",
    "Manor Key",
    "Hydra Humour",
    "Parlor Key",
    "Prison Key",
    "Dragon Tear",
    "White Relic",
    "Black Relic",
    "Red Relic",
    "Blue Relic",
    "Yellow Relic",
    "Green Relic",
    "Life Sparkle",
    "Komodo Scale",
    "Star Fragment",
    "Card Key",
    "Explosive",
    "Tear of Hate",
    "Tear of Love",
    "Station Pass",
    "Ancient Fruit",
    "MementoPendant",
    "Handle",
    "Garai Keepsake",
    "Decor Shield",
    "Fiddler Crab",
    "Chrono Cross",
    "Safety Gear",
    "SapphireBrooch",
    "Prop Sword",
    "Dragon Emblem",
    "Book of Poems",
    "Medical Book",
    "Hero's Medal",
    "Time Egg",
    "S54",
    "S55",
    "S56",
    "S57",
    "S58",
    "S59",
    "S60",
    "Relief Charm",
    "Time Shifter",
    "Smith Spirit",
    "S64"
};

const char* varBit1[] = {
    //1800
    "Cliff Fall Save Call",
    "Friends Kicked Off",
    "Kid's Speech",
    "Leena's Speech",
    "Cape Enemy Defeated",
    "Poshul Befriended",
    "Mojo Befriended",
    "End of time Found",
    "Found DivDragFalls",
    "Found SecretIsland",
    "Metamorph",
    "LightFX Debug",
    "FloatingFX Debug",
    "",
    "Ind. Menu Start",
    "Ind. Debug Flag",
    //1820
    "SisMemo=MaxPowerWeap",
    "TreasGuardBehindFalls",
    "SisMemo=WindProtection",
    "Dwarf Trio Escapes",
    "Hi-Ho Tank Blows Up",
    "Meet With Arni Seaman",
    "Meet Arni Seaman 2x",
    "Stole Steel at Falls",
    "Sis.Rosetta Life Lost",
    "Dwarves go to Woods",
    "Dwarves Draw Line",
    "Rebirth lost Green",
    "WatDragB SkellyBone",
    "Blue Relic Obtained",
    "Ran From Cavern Boss",
    "Def. RecOfFate Guard",
    //1840
    "Opened Big Hole",
    "Dwarf Chief Warning",
    "Beat Hole Smallfry",
    "BubbaBeeba Beaten",
    "Wide Open Space",
    "Beat Treetop Boss",
    "Beat UnderTree Boss",
    "Pentapus KO'ed",
    "Razzly befriended",
    "2xfall.No beat Penta",
    "Fled Hydra Battle",
    "Beeba's Revenge",
    "BubbaBeeba Appears",
    "BubbaBeeba Battle2",
    "BubbaBeeba Beaten",
    "BubbaBeeba Saved",
    //1860
    "Beeba Flute Played",
    "Saw the Flying Bug",
    "Fled Dwarf Battle",
    "Hydra Death Fairy",
    "Wierd Plant Explan.",
    "Hydra Dwarf Platoon",
    "Route4 Beeba Up",
    "Route4 Beeba Down",
    "Flower in Forest",
    "Beat Forest Goblin",
    "SkellyBone in Hole",
    "ReceivedSafetyGear",
    "DwarfLeader Downed",
    "HobGob Bros Fled",
    "Fled from HobGobs",
    "Left Dwarf Forest",
    //1880
    "Saw Bar Event",
    "MaxStr.Lure Search",
    "FlyingFox FacePass",
    "Got Green Tinkler",
    "Kid is Befriended",
    "XchangerSkellyBone",
    "Took Astral Charm",
    "PermittedToUseBoat",
    "Korcha Befriended",
    "Macha Befriended",
    "Entered Doc's Room",
    "Departed Guldove",
    "TakeMel'sChallenge",
    "DefyMel'sChallenge",
    "MidwayInMel'sEvent",
    "Heard ShrineMaiden",
    //18A0
    "Macha's Lecture",
    "Handed Hydra Humor",
    "Returned to Doc's",
    "Hit South SeaThing",
    "Guldove Recall",
    "FlyingFoxFacePassA",
    "Elements Stolen",
    "ShowedDragonEmblem",
    "Steena Befriended",
    "Doc Befriended",
    "Mel Befriended",
    "Got 6DragRelics",
    "DemiMerchantBoat",
    "Mel not go Shrine",
    "Dragon Tear Story",
    "Got Dragon Emblem",
    //18C0
    "Took Orlha's Promise",
    "Orlha Befriended",
    "SpokeToShrineMaiden",
    "Shown Medical Book",
    "Heard Kid is Alive",
    "Orlha's Sister Tia",
    "Mel Flees MerchTower",
    "End of Mel's Event",
    "HardJourneyContinues",
    "End of Twin's Story",
    "Korcha & Korcha Event",
    "Macha & Macha Event",
    "Read Mel's Letter",
    "Orcha & Orcha Event",
    "Doc & Doc Event",
    "Doc Speaks to Nurse",
    //18E0
    "ErthDrgA Subt.1Treas.",
    "ErthDrgA Geysered Up",
    "ErthDrgA LeftJet Stop",
    "ErthDrgA RghtJet Stop",
    "ErthDrgA MidJet Stop",
    "ErthDrgA Restart Jets",
    "ErthDrg3 Common Help",
    "ErthDrg FellFromHigh",
    "Yellow Relic Received",
    "ErthDrg Low.Inv.Start",
    "ErthDrg Lower Guard",
    "Explosives Received",
    "Subt. Guard Descended",
    "EthDrgGotGuardRainbow",
    "",
    "",
    //1900
    "Sea Of Eden - On Isle",
    "Dead Sea Ruins - Boat",
    "Death's Door Unsealed",
    "Moored at Fate1 Isle",
    "Moored at Fate2 Isle",
    "Moored at Fate3 Isle",
    "Moored at Chronopolis",
    "",
    "To World Time Forgot",
    "Station Pass Taken",
    "HighwayMan",
    "DeadSea Lavos Info.",
    "DeadSea Hero Sword",
    "EnteringTowerOfGeddon",
    "Highway Rubbish",
    "Station Mr.Twilight",
    //1920
    "StageRuin MARLE Phantom",
    "Wing Ruin LUCCA Phantom",
    "Library CRONO Phantom",
    "Leene Square 3 Phantoms",
    "Those Trapped in Time",
    "Alt.Dimen. Leene Square",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    //1940
    "T.CHESTS A:Chest1",
    "T.CHESTS A:Chest1",
    "T.CHESTS A:Chest2",
    "T.CHESTS A:Chest1",
    "T.CHESTS A:Chest2",
    "T.CHESTS A:Chest1",
    "T.CHESTS A:Chest1",
    "T.CHESTS A:Chest2",
    "T.CHESTS A:Chest1",
    "T.CHESTS A:Chest2",
    "T.CHESTS A:Chest1",
    "T.CHESTS A:Chest2",
    "T.CHESTS A:Chest1",
    "T.CHESTS A:Chest1",
    "",
    "",
    //1960
    "T.CHESTS A:Chest1",
    "T.CHESTS A:Chest2",
    "T.CHESTS A:Chest1",
    "T.CHESTS A:Chest2",
    "T.CHESTS A:Chest1",
    "T.CHESTS A:Chest1",
    "T.CHESTS A:Chest1",
    "T.CHESTS A:Chest2",
    "T.CHESTS A:Chest1",
    "T.CHESTS A:Chest2",
    "T.CHESTS A:Chest1",
    "T.CHESTS A:Chest2",
    "T.CHESTS A:Chest3",
    "T.CHESTS A:Chest4",
    "",
    "",
    //1980
    "T.CHESTS A:Chest1",
    "T.CHESTS A:Chest1",
    "T.CHESTS A:Chest2",
    "T.CHESTS A:Chest3",
    "T.CHESTS A:Chest1",
    "T.CHESTS A:Chest2",
    "T.CHESTS A:Chest3",
    "T.CHESTS A:Chest1",
    "T.CHESTS A:Chest2",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    //19A0
    "T.CHESTS B:Chest1",
    "T.CHESTS B:Chest1",
    "T.CHESTS B:Chest2",
    "T.CHESTS B:Chest1",
    "T.CHESTS B:Chest2",
    "T.CHESTS B:Chest1",
    "T.CHESTS B:Chest2",
    "T.CHESTS B:EarthDragB Subt.1 Chest1",
    "T.CHESTS B:EarthDragB Subt.2 Chest1",
    "T.CHESTS B:EarthDragB Subt.2 Chest2",
    "",
    "",
    "",
    "",
    "",
    "",
    //19C0
    "T.CHESTS B:HydraB1 Chest1",
    "T.CHESTS B:HydraB1 Chest2",
    "T.CHESTS B:HydraB2 Chest1",
    "T.CHESTS B:HydraB3 Chest1",
    "T.CHESTS B:HydraB3 Chest2",
    "T.CHESTS B:HydraB4 Chest1",
    "T.CHESTS B:HydraB5 Chest2",
    "T.CHESTS B:HydraB9 Chest1",
    "T.CHESTS B:Tree RouteB Chest1",
    "T.CHESTS B:Inside TreeB Chest1",
    "",
    "",
    "",
    "",
    "",
    "",
    //19E0
    "Steena & Steena",
    "Steena & Direa",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    //1A00
    "Moored at Marbule A",
    "Moored IsleOfDamnedA",
    "Moored EarthDragIs.A",
    "Moored WaterDragIs.A",
    "Moored SkyDragonIs.A",
    "Moored Hermit'sHideA",
    "",
    "Moored at ArniVill.A",
    "Moored at Termina A",
    "Moored Pyre Shore A",
    "Moored Dario WoodsA",
    "Moored ViperBluffsA",
    "",
    "",
    "Harbored from WorldA",
    "On Land A",
    //1A20
    "Moored in Marbule B",
    "Moored IsleOfDamnedB",
    "Moored EarthDragIs.B",
    "Moored WaterDragIs.B",
    "Moored SkyDragonIs.B",
    "Moored Hermit'sHideB",
    "",
    "Moored at ArniVill.B",
    "Moored at Termina B",
    "Moored Pyre Shore B",
    "Moored Dario WoodsB",
    "Moored ViperBluffsB",
    "",
    "",
    "HarboredFromWorldB",
    "On Land B",
    //1A40
    "T.CHESTS B:Chest1",
    "T.CHESTS B:Chest2",
    "T.CHESTS B:Chest3",
    "T.CHESTS B:Chest1",
    "T.CHESTS B:Chest2",
    "T.CHESTS B:Chest1",
    "T.CHESTS B:Chest2",
    "T.CHESTS B:Chest3",
    "T.CHESTS B:Chest1",
    "T.CHESTS B:Chest2",
    "T.CHESTS B:Chest1",
    "T.CHESTS B:Chest2",
    "T.CHESTS B:Chest1",
    "T.CHESTS B:Chest2",
    "",
    "",
    //1A60
    "Fled LifeSparkle Battle",
    "Entrance Guards Left",
    "Blew Flute At Tree Top",
    "Defeated Bone Hydra",
    "Beeba's Ask The Strong",
    "Razzly's Guidance",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    //1A80
    "Fairies Annihilated",
    "Beat WaterDragRm.Guard",
    "Up On Blue Water Isle",
    "Sworn on a Fiery Night",
    "Arni Seaman's NightOut",
    "End WaterDragIsle Act",
    "AncDragFort Bone Taken",
    "WaterDragPlatoonRainbow",
    "Dried Up Water Source",
    "Night at BlueWaterIs.",
    "Sis.Rozetta Down Deep",
    "",
    "",
    "",
    "",
    ""
};

const char* varBit2[] = {
    //1C00
    "WORLD1:Cleared Lizard Rock",
    "WORLD1:Cleared Fossil Valley",
    "WORLD1:Collected Scales",
    "WORLD1:Moved LizRock Shell",
    "WORLD1:Cleared Mt. Pyre",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    //$1C20
    "BRANCH1:Forest Route",
    "BRANCH1:Front Gate Route",
    "BRANCH1:Cliff face Route",
    "BRANCH1:Went to HydraM",
    "BRANCH1:Went to HermitH",
    "BRANCH1:Went to Wat.Drag.Isle",
    "BRANCH1:Ditched Kid",
    "BRANCH1:Met Korcha",
    "BRANCH1:Heard Prophet",
    "BRANCH1:Kid Revived",
    "BRANCH1:Went Alt.Dimen.",
    "BRANCH1:Marbule Restored",
    "BRANCH1:Razzly to HermitH",
    "BRANCH1:Defeat S&P at Pyre",
    "",
    "",
    //1C40
    "WORLD1:Cleared Lizard RockB",
    "WORLD1:Cleared Fossil ValleyB",
    "WORLD1:WorldB to Ranch",
    "WORLD1:Cleared Mt. Pyre",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    //1C60
    "GLOBAL1:Serge Revived",
    "GLOBAL1:Got Dragon Tear",
    "GLOBAL1:Hatched Drag Egg",
    "GLOBAL1:Masamune MaxPower",
    "GLOBAL1:Rebuilt ViperManor",
    "GLOBAL1:Saved Orphan Kid",
    "GLOBAL1:Concert Midway",
    "GLOBAL1:Concert Over",
    "GLOBAL1:Marbule Annihiled",
    "GLOBAL1:Got Master Hammer",
    "",
    "",
    "",
    "",
    "",
    ""
};


char itemDefaultNameBuffer[256];

const char* GetElementName(unsigned int idx)
{
    if(idx < (sizeof(ElementList) / sizeof(const char*)))
        return ElementList[idx];
    return NULL;
}

const char* GetCommonItemName(unsigned int idx)
{
    if(idx < (sizeof(CommonItemList) / sizeof(const char*)))
        return CommonItemList[idx];
    return NULL;
}

const char* GetRareItemName(unsigned int idx)
{
    if(idx < (sizeof(RareItemList) / sizeof(const char*)))
        return RareItemList[idx];
    return NULL;
}

const char* GetItemName(unsigned int idx)
{
    if(idx < 0x200)
        return GetCommonItemName(idx);
    if(idx < 0x400)
        return GetElementName(idx - 0x200);
    if(idx < 0x500)
        return GetRareItemName(idx - 0x400);

    sprintf(itemDefaultNameBuffer, "Unamed item %d", idx);
    return itemDefaultNameBuffer;
}

const char* GetVarBitName(unsigned int idx)
{
    // 1800 - 1A90
    if((idx >= 0x1800) && (idx < 0x1A90))
    {
        unsigned int realIdx = idx - 0x1800;
        realIdx = (((realIdx>>4)/2)<<4) + (realIdx & 0xF);
        return varBit1[realIdx];
    }

    //1C00 - 1C70
    if((idx >= 0x1C00) && (idx < 0x1C70))
    {
        unsigned int realIdx = idx - 0x1C00;
        realIdx = (((realIdx>>4)/2)<<4) + (realIdx & 0xF);
        return varBit2[realIdx];
    }

    return NULL;
}