#include <stdlib.h>
#include "CCRoomName.h"

const char* CCRoomName_CD1[] = 
{
    "Main debug room",
    "Kato's room",
    "Miyakawa's room",
    "Kigoshi's room",
    "Saito's room",
    "Uchimichi's room",
    "Yoshii's room",
    "Chiba's room",
    "Title screen",
    "Game Over screen",
    "Demo scene - Shadow Forest Entrance",
    "Demo scene - Shadow Forest Giant Tree",
    "Demo scene - Viper Manor Study Bridge (Night)",
    "Demo scene - Viper Manor Study with Harle",
    "Demo scene - Hydra Marshes (bg music - Dilemma) with Solt and Peppor",
    "Demo scene - Hydra Marshes (bg music - Dilemma)",
    "Demo scene - Termina Entrance",
    "Demo scene - Termina Fortune Teller",
    "Demo scene - Lucca's Orphanage (maybe unused)",
    "Demo scene - S.S. Invincible",
    "Demo scene - Cape Howl Sunset",
    "Demo scene - Viper Manor (Night)",
    "Fort Dragonia - Second Story Elevator Lobby",
    "Fort Dragonia - Second Story Teleporter Room",
    "Fort Dragonia - Second Story Side-Staircase",
    "Fort Dragonia - Second Story Crystal",
    "Fort Dragonia - Dragon Tear Chamber Station",
    "Arni (Home World)",
    "Arni (Another World)",
    "Arni - Serge's House Living Room (Home)",
    "Arni - Serge's House Living Room (Another)",
    "Arni - Serge's Room (Home)",
    "Arni - Serge's Room (Another)",
    "Arni - Chief's Meadow (Home)",
    "Arni - Chief's Meadow (Another)",
    "Arni - Chief's Hut (Home)",
    "Arni - Chief's Hut (Another)",
    "Arni Dock (Home)",
    "Arni Dock (Another)",
    "Arni - Belcha's Kitchen (Home)",
    "Arni - Cafe Fleur (Another)",
    "Arni - Belcha's Kitchen Bed (Home)",
    "Arni - Cafe Fleur Bed (Another)",
    "Arni - Kiki's Dad's Room (Home)",
    "Arni - Kiki's Dad's Room (Another)",
    "Arni - Leena's House (Home)",
    "Arni - Leena's House (Another)",
    "Arni - Kiki's House (Home)",
    "Arni - Kiki's House (Another)",
    "SCENE - Sea of Eden - Wazuki takes Serge to Chronopolis",
    "Lizard Rock Entrance (Home)",
    "Lizard Rock Entrance (Another)",
    "Lizard Rock East (Home)",
    "Lizard Rock East (Another)",
    "Lizard Rock South (Home)",
    "Lizard Rock South (Another)",
    "Opassa Beach (Home)",
    "Opassa Beach (Another)",
    "Cape Howl Entrance (Home)",
    "Cape Howl Entrance (Another)",
    "Cape Howl Cape (Home)",
    "Cape Howl Cape (Another)",
    "Cape Howl Cape Sunset (Another)",
    "Cape Howl Rock (Home)",
    "Cape Howl Grave (Another)",
    "Cape Howl Grave Sunset (Another)",
    "Fossil Valley Entrance (Home)",
    "Fossil Valley Entrance (Another)",
    "Fossil Valley Skeleton (Home)",
    "Fossil Valley Skeleton (Another)",
    "Fossil Valley Entrance Post-Lynx Invasion (Another)",
    "Termina Cemetery (Home)",
    "Termina Cemetery (Another)",
    "Termina Fortune Teller (Home)",
    "Termina Fortune Teller (Another)",
    "Termina Dragoon Quarter (Home)",
    "Termina Dragoon Quarter (Another)",
    "Termina Entrance (Home)",
    "Termina Entrance (Another)",
    "Termina Dock (Home)",
    "Termina Dock (Another)",
    "Termina - Lisa's Element Shop (Home)",
    "Termina - Lisa's Element Shop (Another)",
    "Termina - Lisa's Element Shop Bed (Home)",
    "Termina - Lisa's Element Shop Bed (Another)",
    "Termina - Dragon's Tail Bar (Home)",
    "Termina - Dragon's Tail Bar (Another)",
    "Termina - Dragon's Tail Bar Back Room (Home)",
    "Termina - Dragon's Tail Bar Back Room (Another)",
    "Termina - Sick Girl's House (Home)",
    "Termina - Sick Girl's House (Another)",
    "Termina - Skelly's House (Home)",
    "Termina - Skelly's House (Another)",
    "Termina - Zappa's House (Home)",
    "Termina - Zappa's House (Another)",
    "Termina - Zappa's Guest Room (Home)",
    "Termina - Zappa's Guest Room (Another)",
    "Termina - Glenn's House (Home)",
    "Termina - Glenn's House (Another)",
    "Termina Cemetery House (Home)",
    "Termina Cemetery House (Another)",
    "Termina Inn (Home)",
    "Termina Inn (Another)",
    "Termina Inn Suite One (Home)",
    "Termina Inn Suite One (Another)",
    "Termina Inn Suite Two (Home)",
    "Termina Inn Suite Two (Another)",
    "Termina - Van's Room (Home)",
    "Termina - Van's Room (Another)",
    "Termina - Van's House (Home)",
    "Termina - Gogh's Room (Another)",
    "Termina - Van's House (Another)",
    "Termina Fortune Teller (Before Viper Manor Break-in) (Another)",
    "Termina Cemetery (Another)",
    "Termina Dock (Another)",
    "Termina - Magical Dreamers Ship Deck (Another)",
    "Termina - Magical Dreamers Ship - Nikki's Room (Another)",
    "Termina - Magical Dreamers Ship - Miki's Room (Another)",
    "Termina Entrance (Post-Invasion) (Another)",
    "SCENE - Karsh thinks of Riddel in the Dragoon Quarter",
    "Termina Dragoon Quarter (Disabled Exits) (Another)",
    "SCENE - The party sails through the Dragoon Quarter to Viper Manor",
    "Shadow Forest (Home)",
    "Shadow Forest (Another)",
    "Shadow Forest Second Shade (Home)",
    "Shadow forest Second Shade (Another)",
    "Shadow Forest Waterfall (Home)",
    "Shadow Forest Waterfall (Another)",
    "Shadow Forest Grotto (Home)",
    "Shadow Forest Grotto (Another)",
    "Shadow Forest Giant Tree (Home)",
    "Shadow Forest Giant Tree (Another)",
    "Shadow Forest Waterfall (Before Viper Manor) (Another)",
    "Shadow Forest Tree River (Home)",
    "Shadow Forest Tree River (Another)",
    "Shadow Forest River Current (Home)",
    "Shadow Forest River Current (Another)",
    "Shadow Forest Well Base (Home)",
    "Shadow Forest Well Base (Another)",
    "Viper Manor Drainage Duct (Home)",
    "Viper Manor Drainage Duct (Another)",
    "Viper Manor Gate (Home)",
    "Viper Manor Gate (Another)",
    "Viper Manor Bluffs Dock (Home)",
    "Viper Manor Bluffs Dock (Another)",
    "Viper Manor Bluffs Second Ascent (Home)",
    "Viper Manor Bluffs Second Ascent (Another)",
    "Viper Manor Bluffs Final Ascent (Home)",
    "Viper Manor Bluffs Final Ascent (Another)",
    "Viper Manor Courtyard (Home)",
    "Viper Manor Courtyard (Another)",
    "Viper Manor Stable Courtyard (Another)",
    "Viper Manor Stables",
    "Viper Manor Foyer",
    "Viper Manor - Karsh's Room",
    "Viper Manor - ZOAH'S ROOM",
    "Viper Manor - Norris's Room",
    "Viper Manor - Harle's Room",
    "Viper Manor - Throne Room",
    "Viper Manor - Bridge to Study",
    "Viper Manor - Bridge to Study (Night)",
    "Viper Manor Study",
    "Viper Manor Balcony (Night)",
    "Viper Manor - Executive Hallway",
    "Viper Manor Balcony",
    "Viper Manor - Viper's Room",
    "Viper Manor - Riddel's Room",
    "Viper Manor Basement Hall",
    "Viper Manor Barracks",
    "Viper Manor Mess Hall",
    "Viper Manor Treasury",
    "Viper Manor Armament",
    "Viper Manor Jail Cells (Home)",
    "Viper Manor Jail Cells (Another)",
    "Viper Manor - Fargo's Cell",
    "Viper Manor - Interrogation Chamber (Home)",
    "Viper Manor - Interrogation Chamber (Another)",
    "Viper Manor Sewers - Main Complex (Home)",
    "Viper Manor Sewers - Main Complex (Another)",
    "Viper Manor Sewers - Pump Controls (Home)",
    "Viper Manor Sewers - Pump Controls (Another)",
    "Viper Manor Sewers - Entrance (Home)",
    "Viper Manor Sewers - Entrance (Another)",
    "Viper Manor - Bridge to Treasure Tower",
    "Viper Manor - Treasure Tower",
    "SCENE - Belthasar explains dimensions",
    "Viper Manor Balcony Edge (Night)",
    "Viper Manor - Jail Cell",
    "Viper Manor - Throne Room (After Invasion)",
    "Viper Manor Foyer (Escape from Porre)",
    "Viper Manor Stables Courtyard (Escape from Porre)",
    "Viper Manor Basement Hall (During Break-In)",
    "Viper Manor Foyer (During Break-In)",
    "Viper Manor Treasury (maybe After Invasion)",
    "Viper Manor Gates (After Invasion)",
    "Viper Manor Courtyard (After Invasion)",
    "Viper Manor Study (After Invasion)",
    "Viper Manor Gates (Dario's Restoration) (Home)",
    "Viper Manor Courtyard (Dario's Restoration) (Home)",
    "Viper Manor - Viper's Room (After Invasion)",
    "Viper Manor - Neo Epoch",
    "Viper Manor - Executive Wing (Disabled Exits)",
    "Viper Manor Mess Hall (After Invasion)",
    "Guldove Dock (Home)",
    "Guldove Dock (Before Going with Macha) (Another)",
    "Guldove Shop Exterior (Home)",
    "Guldove Shop Exterior (Another)",
    "Guldove - Macha's Tent Upper Exterior (Home)",
    "Guldove - Macha's Tent Upper Exterior (Another)",
    "Guldove - Chief's Tent Exterior (Home)",
    "Guldove - Chief's Tent Exterior (Another)",
    "Guldove - Doc's House (Home)",
    "Guldove - Doc's House (Another)",
    "Guldove - Doc's Beds (Home)",
    "Guldove - Doc's Beds (Another)",
    "Guldove - Element Shop (Home)",
    "Guldove - Element Shop (Another)",
    "Guldove Bar (Home)",
    "Guldove Bar (Another)",
    "Guldove - Macha's Tent (Home)",
    "Guldove - Macha's Tent (Another)",
    "Guldove - Macha's Tent Lower Level (Home)",
    "Guldove - Macha's Tent Lower Level (Another)",
    "Guldove - Chief's Tent (Home)",
    "Guldove - Chief's Tent (Another)",
    "Guldove - Doc's House (After Lynx) (Another)",
    "Guldove - Doc's Beds (After Lynx) (Home)",
    "SCENE - Discussion with Kid and Korcha after escape from Lynx",
    "Guldove Dock (Another)",
    "SCENE - Orlha battles Porre soldiers",
    "Hydra Marshes Entrance (Home)",
    "Hydra Marshes Entrance (Another)",
    "Hydra Marshes Northeast of Entrance (Home)",
    "Hydra Marshes Northeast of Entrance (Another)",
    "Hydra Marshes Upper Area (Home)",
    "Hydra Marshes Upper Area (Another)",
    "Hydra Marshes Northwest of Entrance (Home)",
    "Hydra Marshes Northwest of Entrance (Another)",
    "Hydra Marshes - Branches (Home)",
    "Hydra Marshes - Branches (Another)",
    "Hydra Marshes - Beeba Pad (Home)",
    "Hydra Marshes - Beeba Pad (Another)",
    "Hydra Marshes - Wingapede Pad (Home)",
    "Hydra Marshes - Wingapede Pad (Another)",
    "Hydra Marshes - Hollow Tree (Home)",
    "Hydra Marshes - Hollow Tree (Another)",
    "Hydra Marshes - Quadffid Pool (Home)",
    "Hydra Marshes - Quadffid Pool (Another)",
    "Hydra Marshes - Hydra Pool (Home)",
    "Hydra Marshes - Hydra Pool (Another)",
    "El Nido (Home)",
    "El Nido (Another)",
    "El Nido Main Island (Home)",
    "El Nido Main Island (Another)",
    "Dead Sea",
    "Sea of Eden (Defense Activated)",
    "Divine Dragon Falls Cave (Home)",
    "Divine Dragon Falls Cave (Another)",
    "Sea of Eden (Home)",
    "Sea of Eden (Chronopolis Exposed) (Another)",
    "Divine Dragon Falls (Home)",
    "Divine Dragon Falls (Another)",
    "S.S. Invincible Deck",
    "S.S. Invincible First Level (During Ghost Siege)",
    "S.S. Invincible Second Level",
    "S.S. Invincible Hull (During Ghost Siege)",
    "S.S. Invincible Kitchen",
    "S.S. Invincible Storage (During Ghost Siege)",
    "S.S. Invincible Cannon Hold",
    "S.S. Invincible Hull",
    "S.S. Invincible Hammocks",
    "S.S. Invincible Special Deck SCENE - Fargo reminisces",
    "S.S. Invincible Deck (With Ghost Ship)",
    "S.S. Invincible First Level",
    "S.S. Invincible Mess Hall",
    "S.S. Invincible First Level Beds",
    "S.S. Invincible Second Level Beds",
    "S.S. Invincible Storage",
    "S.S. Invincible - Captain's Quarters",
    "Hermit's Hideaway (Home)",
    "Hermit's Hideaway (Another)",
    "Hermit's Hideaway Interior (Home)",
    "Hermit's Hideaway Interior (Another)",
    "Hermit's Hideaway Interior (Another)",
    "Hermit's Hideaway (Home)",
    "Water Dragon Isle (Home)",
    "Water Dragon Isle (Another)",
    "Water Dragon Isle Fairy Tree (Dwarf Attack) (Home)",
    "Water Dragon Isle Fairy Tree (Another)",
    "Water Dragon Isle Interior (Dwarf Attack) (Home)",
    "Water Dragon Isle Falls (Dwarf Attack) (Home)",
    "Water Dragon Isle Water Dragon (Home)",
    "Water Dragon Isle Fairy Tree (Home)",
    "Water Dragon Isle Interior (Home)",
    "Water Dragon Isle Falls (Home)",
    "Water Dragon Isle Campfire SCENE - Kid talks to Serge",
    "SCENE - The fairies criticize the humans at sundown",
    "Mt. Pyre (Home)",
    "Mt. Pyre (Another)",
    "Mt. Pyre Second Area (Home)",
    "Mt. Pyre Second Area (Another)",
    "Mt. Pyre Third Area (Home)",
    "Mt. Pyre Third Area (Another)",
    "Mt. Pyre Slide Falls (Home)",
    "Mt. Pyre Slide Falls (Another)",
    "Mt. Pyre Lower Passage (Home)",
    "Mt. Pyre Lower Passage (Another)",
    "Mt. Pyre Dragon (Home)",
    "Mt. Pyre Dragon (Another)",
    "Mt. Pyre Slide Falls (Frozen) (Home)",
    "Mt. Pyre Slide Falls (Frozen) (Another)",
    "Fort Dragonia (Home)",
    "Fort Dragonia (Another)",
    "Fort Dragonia Main Bridge (Home)",
    "Fort Dragonia Main Bridge (Another)",
    "Fort Dragonia West Bridge (Home)",
    "Fort Dragonia West Bridge (Another)",
    "Fort Dragonia Northwest Bridge (Home)",
    "Fort Dragonia Northwest Bridge (Another)",
    "Fort Dragonia Northeast Bridge (Home)",
    "Fort Dragonia Northeast Bridge (Another)",
    "Fort Dragonia East Bridge (Home)",
    "Fort Dragonia East Bridge (Another)",
    "Fort Dragonia Lobby (Home)",
    "Fort Dragonia Lobby (Another)",
    "Fort Dragonia Northeast (Home)",
    "Fort Dragonia Northeast (Another)",
    "Fort Dragonia Northeast Second Area (Home)",
    "Fort Dragonia Northeast Second Area (Another)",
    "Fort Dragonia Northeast Third Area (Home)",
    "Fort Dragonia Northeast Third Area (Another)",
    "Fort Dragonia Northeast Crystal (Home)",
    "Fort Dragonia Northeast Crystal (Another)",
    "Fort Dragonia Northwest Area (Home)",
    "Fort Dragonia Northwest Area (Another)",
    "Fort Dragonia Northwest Right Room (Home)",
    "Fort Dragonia Northwest Right Room (Another)",
    "Fort Dragonia Northwest Left Room (Home)",
    "Fort Dragonia Northwest Left Room (Another)",
    "Fort Dragonia Northwest Crystal (Home)",
    "Fort Dragonia Northwest Crystal (Another)",
    "Fort Dragonia West Maze (Home)",
    "Fort Dragonia West Maze (Another)",
    "Fort Dragonia Dragon Tear Chamber (SCENE - Crystal activations) (Home)",
    "Fort Dragonia Dragon Tear Chamber (SCENE - Crystal activations) (Another)",
    "S.S. Zelbess Special Deck (SCENE - Nikki tells Kid about the Magical Dreamers)",
    "Fort Dragonia Dragon Tear Chamber with Broken Statues (SCENE - Karsh, ZOAH, and Marcy find General Viper)",
    "Fort Dragonia West Arrangement Room (Home)",
    "Fort Dragonia West Arrangement Room (Another)",
    "Fort Dragonia East Area (Home)",
    "Fort Dragonia East Area (Another)",
    "Fort Dragonia East Area Selection (Home)",
    "Fort Dragonia East Area Selection (Another)",
    "Fort Dragonia East Area Crystal (Home)",
    "Fort Dragonia East Area Crystal (Another)",
    "Fort Dragonia Central Elevator (Home)",
    "Fort Dragonia Central Elevator (Another)",
    "Fort Dragonia - Second Story Elevator Lobby (Home)",
    "Fort Dragonia - Second Story Elevator Lobby (Another)",
    "Fort Dragonia - Second Story Teleporter Room (Home)",
    "Fort Dragonia - Second Story Teleporter Room (Another)",
    "Fort Dragonia - Second Story Side-Staircase (Home)",
    "Fort Dragonia - Second Story Side-Staircase (Another)",
    "Fort Dragonia - Second Story Crystal (Home)",
    "Fort Dragonia - Second Story Crystal (Another)",
    "Fort Dragonia - Dragon Tear Chamber Station (Home)",
    "Fort Dragonia - Dragon Tear Chamber Station (Another)",
    "Fort Dragonia - Dragon Tear Chamber (Home)",
    "Fort Dragonia - Dragon Tear Chamber (SCENE - Serge confronts Lynx and Viper) (Another)",
    "Fort Dragonia Basement (Home)",
    "Fort Dragonia Basement (Another)",
    "Temporal Vortex",
    "Temporal Vortex - Sprigg's House",
    "Temporal Vortex - Confusion Complex",
    "Temporal Vortex - Chaos",
    "S.S. Zelbess Deck",
    "S.S. Zelbess First Level",
    "S.S. Zelbess Second Level",
    "S.S. Zelbess Inn",
    "S.S. Zelbess Restaurant",
    "S.S. Zelbess Demi-human Room",
    "S.S. Zelbess Hold",
    "S.S. Zelbess Hull (SCENE (05) - Party walks to boat with Magical Dreamers theme)",
    "S.S. Zelbess Comedy Backstage",
    "Crash",
    "S.S. Zelbess - Captain's Quarters",
    "S.S. Zelbess - Casino",
    "S.S. Zelbess - Magical Dreamers Stage (SCENE - Magical Dreamers concert)",
    "S.S. Zelbess - Magical Dreamers Ship Deck",
    "S.S. Zelbess - Magical Dreamers Ship - Nikki's Room",
    "S.S. Zelbess - Magical Dreamers Ship - Miki's Room",
    "S.S. Zelbess - Grand Slam",
    "S.S. Zelbess - Deck (After Marbule Failure)",
    "S.S. Zelbess - Hull (SCENE (05) - Demi-humans begin to row)",
    "SCENE - Magical Dreamers stage opens up to S.S. Zelbess",
    "S.S. Zelbess Inn Attic (SCENE - Demi-human manipulates Casino)",
    "Marbule (Before Restoration) (Home)",
    "Marbule (Another)",
    "Marbule - Black Dragon Cave (Home)",
    "Marbule - Black Dragon Cave (Another)",
    "Marbule - Chief's Cave (Home)",
    "Marbule - Chief's Cave (Another)",
    "Marbule - Witch Doctor's Cave (Home)",
    "Marbule - Witch Doctor's Cave (Another)",
    "Marbule - Bro. of G's Shop (Home)",
    "Marbule - Bro. of G's Shop (Disabled Exits)",
    "Marbule - Mermaid Pirate House (Home)",
    "Marbule - Mermaid Pirate House (Disabled Exits)",
    "Marbule - Child Demi-human's Cave",
    "Marbule (After Restoration) (Home)",
    "Death's Door",
    "Pearly Gates",
    "Earth Dragon Isle (Home)",
    "Earth Dragon Isle (Another)",
    "Earth Dragon Isle Underground (Home)",
    "Earth Dragon Isle Underground (Another)",
    "Earth Dragon Isle Sand Boil (Home)",
    "Earth Dragon Isle Sand Boil (Another)",
    "Earth Dragon Isle - Earth Dragon (Home)",
    "Earth Dragon Isle - Criosphinx (Another)",
    "Isle of the Damned (Home)",
    "Isle of the Damned (Another)",
    "Isle of the Damned Dragon Bones (Home)",
    "Isle of the Damned Dragon Bones (Another)",
    "Isle of the Damned WightKnight (Home)",
    "Isle of the Damned WightKnight (Another)",
    "Isle of the Damned Grave (Home)",
    "Isle of the Damned Grave (Another)",
    "SCENE - Karsh battles the corrupted Dario",
    "Crash (Forbidden Island (Home) (maybe))",
    "Forbidden Island Cabin (Home)",
    "Forbidden Island (Another)",
    "Forbidden Island Cabin (Another)",
    "Sky Dragon Isle (Home)",
    "Sky Dragon Isle (Another)",
    "Sky Dragon Isle Stairway (Home)",
    "Sky Dragon Isle Stairway (Another)",
    "Sky Dragon Isle Summit (Home)",
    "Sky Dragon Isle Summit (Another)",
    "Crash",
    "Crash",
    "Black screen",
    "Crash",
    "El Nido Triangle (Home)",
    "El Nido Triangle (Another)",
    "El Nido Triangle First Area (Home)",
    "Crash",
    "El Nido Triangle Second Area (Home)",
    "Crash",
    "Crash",
    "Gaea's Navel (Home)",
    "Gaea's Navel (After Beating Monsters) (Home)",
    "Gaea's Navel Right from Entrance (Home)",
    "Gaea's Navel Right from Entrance (Another)",
    "Gaea's Navel Right from Last (Home)",
    "Gaea's Navel Right from Last (Another)",
    "Gaea's Navel Green Dragon (Home)",
    "Gaea's Navel Green Dragon (Another)",
    "Dead Sea - Highway Ruins -South-",
    "Dead Sea - Highway Ruins -North-",
    "Dead Sea - City Ruins",
    "Dead Sea - City Ruins - Lithosphere Investigation Report #27",
    "Dead Sea - Tower of Gheddon (SCENE - The party looks up and enters)",
    "Dead Sea - Tower of Gheddon Mall",
    "Dead Sea - Tower of Gheddon Transit",
    "Dead Sea - Tower of Gheddon Theater",
    "Dead Sea - Tower of Gheddon Ruins",
    "Dead Sea - Tower of Gheddon Distortion",
    "Dead Sea - Leene Square",
    "Dead Sea - Nadia's Bell",
    "Dead Sea Special Entrance (SCENE - The party enters the Dead Sea)",
    "Fate Distortion",
    "Marbule Coast (SCENE - The Sky Dragon drops the party off)",
    "Nadia's Bell (SCENE - FATE destroys the Dead Sea)",
    "Crash",
    "Crash",
    "Crash",
    "Chronopolis Lobby (SCENE (02) - Wazuki takes Serge)",
    "Black screen",
    "Crash",
    "Crash",
    "Crash",
    "Crash",
    "Crash",
    "Crash",
    "Crash",
    "Black screen",
    "Crash",
    "SCENE - General Kid ending (Arni)",
    "SCENE - General Kid ending (Viper Manor Executive Wing)",
    "SCENE - General Kid ending (Viper Manor Throne Room)",
    "Black screen",
    "SCENE - Onward, Dragoons! ending (Viper Manor Throne Room)",
    "SCENE - The True Hero ending (Termina - Lisa's Element Shop)",
    "SCENE - The Magical Dreamers ending (Magical Dreamers Stage)",
    "SCENE - The Magical Dreamers ending (Termina Dock)",
    "Black screen",
    "Crash",
    "SCENE - The True Hero ending (Fort Dragonia - Second Story Elevator Lobby)",
    "SCENE - The True Hero ending (Fort Dragonia - Dragon Tear Chamber Station)",
    "SCENE - Onward, Dragoons! ending (S.S. Invincible Special Deck)",
    "SCENE - Onward, Dragoons! ending (S.S. Invincible First Level)",
    "SCENE - Onward, Dragoons! ending (Marbule Witch Doctor's Cave)",
    "SCENE - The True Hero ending (Viper Manor Mess Hall)",
    "SCENE - New Beginnings ending (Marbule (After Restoration))",
    "SCENE - New Beginnings ending (Pearly Gates)", // 505
    "",
    "",
    "",
    "",
    "", // 510
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "", // 520
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "", // 530
    "Bend of time - 1",
    "Bend of time - 2",
    "Chrono Cross logo",
    "",
    "", // 535
    "",
    "",
    "Leene Square",
    "SCENE - Oracle of fate turns black",
    "SCENE - Dark Serge and Kid in Chronopolis", // 540
    "SCENE - Dark Serge in frozen flame room",
    "SCENE - Viper headmaster",
    "SCENE - Termina - Dark serge",
    "SCENE - Termina tarvern- Dark serge"
};

const char* CCRoomName_CD2[] = 
{
    "Main debug room",
    "Crash",
    "Crash",
    "Crash",
    "Crash",
    "Black screen",
    "Crash",
    "Crash",
    "Title screen",
    "Game Over screen",
    "Demo scene - Shadow Forest Entrance",
    "Demo scene - Shadow Forest Giant Tree",
    "Demo scene - Viper Manor Study Bridge (Night)",
    "Demo scene - Viper Manor Study with Harle",
    "Demo scene - Hydra Marshes (bg music - Dilemma) with Solt and Peppor",
    "Demo scene - Hydra Marshes (bg music - Dilemma)",
    "Demo scene - Termina Entrance",
    "Demo scene - Termina Fortune Teller",
    "Demo scene - Lucca's Orphanage (maybe unused)",
    "Demo scene - S.S. Invincible",
    "Demo scene - Cape Howl Sunset",
    "Demo scene - Viper Manor (Night)",
    "Fort Dragonia - Second Story Elevator Lobby",
    "Fort Dragonia - Second Story Teleporter Room",
    "Fort Dragonia - Second Story Side-Staircase",
    "Fort Dragonia - Second Story Crystal",
    "Fort Dragonia - Dragon Tear Chamber Station",
    "Arni (Home World)",
    "Arni (Another World)",
    "Arni - Serge's House Living Room (Home)",
    "Arni - Serge's House Living Room (Another)",
    "Arni - Serge's Room (Home)",
    "Arni - Serge's Room (Another)",
    "Arni - Chief's Meadow (Home)",
    "Arni - Chief's Meadow (Another)",
    "Arni - Chief's Hut (Home)",
    "Arni - Chief's Hut (Another)",
    "Arni Dock (Home)",
    "Arni Dock (Another)",
    "Arni - Belcha's Kitchen (Home)",
    "Arni - Cafe Fleur (Another)",
    "Arni - Belcha's Kitchen Bed (Home)",
    "Arni - Cafe Fleur Bed (Another)",
    "Arni - Kiki's Dad's Room (Home)",
    "Arni - Kiki's Dad's Room (Another)",
    "Arni - Leena's House (Home)",
    "Arni - Leena's House (Another)",
    "Arni - Kiki's House (Home)",
    "Arni - Kiki's House (Another)",
    "SCENE - Sea of Eden - Wazuki takes Serge to Chronopolis",
    "Lizard Rock Entrance (Home)",
    "Lizard Rock Entrance (Another)",
    "Lizard Rock East (Home)",
    "Lizard Rock East (Another)",
    "Lizard Rock South (Home)",
    "Lizard Rock South (Another)",
    "Opassa Beach (Home)",
    "Opassa Beach (Another)",
    "Cape Howl Entrance (Home)",
    "Cape Howl Entrance (Another)",
    "Cape Howl Cape (Home)",
    "Cape Howl Cape (Another)",
    "Cape Howl Cape Sunset (Another)",
    "Cape Howl Rock (Home)",
    "Cape Howl Grave (Another)",
    "Cape Howl Grave Sunset (Another)",
    "Fossil Valley Entrance (Home)",
    "Fossil Valley Entrance (Another)",
    "Fossil Valley Skeleton (Home)",
    "Fossil Valley Skeleton (Another)",
    "Fossil Valley Entrance Post-Lynx Invasion (Another)",
    "Termina Cemetery (Home)",
    "Termina Cemetery (Another)",
    "Termina Fortune Teller (Home)",
    "Termina Fortune Teller (Another)",
    "Termina Dragoon Quarter (Home)",
    "Termina Dragoon Quarter (Another)",
    "Termina Entrance (Home)",
    "Termina Entrance (Another)",
    "Termina Dock (Home)",
    "Termina Dock (Another)",
    "Termina - Lisa's Element Shop (Home)",
    "Termina - Lisa's Element Shop (Another)",
    "Termina - Lisa's Element Shop Bed (Home)",
    "Termina - Lisa's Element Shop Bed (Another)",
    "Termina - Dragon's Tail Bar (Home)",
    "Termina - Dragon's Tail Bar (Another)",
    "Termina - Dragon's Tail Bar Back Room (Home)",
    "Termina - Dragon's Tail Bar Back Room (Another)",
    "Termina - Sick Girl's House (Home)",
    "Termina - Sick Girl's House (Another)",
    "Termina - Skelly's House (Home)",
    "Termina - Skelly's House (Another)",
    "Termina - Zappa's House (Home)",
    "Termina - Zappa's House (Another)",
    "Termina - Zappa's Guest Room (Home)",
    "Termina - Zappa's Guest Room (Another)",
    "Termina - Glenn's House (Home)",
    "Termina - Glenn's House (Another)",
    "Termina Cemetery House (Home)",
    "Termina Cemetery House (Another)",
    "Termina Inn (Home)",
    "Termina Inn (Another)",
    "Termina Inn Suite One (Home)",
    "Termina Inn Suite One (Another)",
    "Termina Inn Suite Two (Home)",
    "Termina Inn Suite Two (Another)",
    "Termina - Van's Room (Home)",
    "Termina - Van's Room (Another)",
    "Termina - Van's House (Home)",
    "Termina - Gogh's Room (Another)",
    "Termina - Van's House (Another)",
    "Termina Fortune Teller (Before Viper Manor Break-in) (Another)",
    "Termina Cemetery (Another)",
    "Termina Dock (Another)",
    "Termina - Magical Dreamers Ship Deck (Another)",
    "Termina - Magical Dreamers Ship - Nikki's Room (Another)",
    "Termina - Magical Dreamers Ship - Miki's Room (Another)",
    "Termina Entrance (Post-Invasion) (Another)",
    "SCENE - Karsh thinks of Riddel in the Dragoon Quarter",
    "Termina Dragoon Quarter (Disabled Exits) (Another)",
    "SCENE - The party sails through the Dragoon Quarter to Viper Manor",
    "Shadow Forest (Home)",
    "Shadow Forest (Another)",
    "Shadow Forest Second Shade (Home)",
    "Shadow forest Second Shade (Another)",
    "Shadow Forest Waterfall (Home)",
    "Shadow Forest Waterfall (Another)",
    "Shadow Forest Grotto (Home)",
    "Shadow Forest Grotto (Another)",
    "Shadow Forest Giant Tree (Home)",
    "Shadow Forest Giant Tree (Another)",
    "Shadow Forest Waterfall (Before Viper Manor) (Another)",
    "Shadow Forest Tree River (Home)",
    "Shadow Forest Tree River (Another)",
    "Shadow Forest River Current (Home)",
    "Shadow Forest River Current (Another)",
    "Shadow Forest Well Base (Home)",
    "Shadow Forest Well Base (Another)",
    "Viper Manor Drainage Duct (Home)",
    "Viper Manor Drainage Duct (Another)",
    "Viper Manor Gate (Home)",
    "Viper Manor Gate (Another)",
    "Viper Manor Bluffs Dock (Home)",
    "Viper Manor Bluffs Dock (Another)",
    "Viper Manor Bluffs Second Ascent (Home)",
    "Viper Manor Bluffs Second Ascent (Another)",
    "Viper Manor Bluffs Final Ascent (Home)",
    "Viper Manor Bluffs Final Ascent (Another)",
    "Viper Manor Courtyard (Home)",
    "Viper Manor Courtyard (Another)",
    "Viper Manor Stable Courtyard (Another)",
    "Viper Manor Stables",
    "Viper Manor Foyer",
    "Viper Manor - Karsh's Room",
    "Viper Manor - ZOAH'S ROOM",
    "Viper Manor - Norris's Room",
    "Viper Manor - Harle's Room",
    "Viper Manor - Throne Room",
    "Viper Manor - Bridge to Study",
    "Viper Manor - Bridge to Study (Night)",
    "Viper Manor Study",
    "Viper Manor Balcony (Night)",
    "Viper Manor - Executive Hallway",
    "Viper Manor Balcony",
    "Viper Manor - Viper's Room",
    "Viper Manor - Riddel's Room",
    "Viper Manor Basement Hall",
    "Viper Manor Barracks",
    "Viper Manor Mess Hall",
    "Viper Manor Treasury",
    "Viper Manor Armament",
    "Viper Manor Jail Cells (Home)",
    "Viper Manor Jail Cells (Another)",
    "Viper Manor - Fargo's Cell",
    "Viper Manor - Interrogation Chamber (Home)",
    "Viper Manor - Interrogation Chamber (Another)",
    "Viper Manor Sewers - Main Complex (Home)",
    "Viper Manor Sewers - Main Complex (Another)",
    "Viper Manor Sewers - Pump Controls (Home)",
    "Viper Manor Sewers - Pump Controls (Another)",
    "Viper Manor Sewers - Entrance (Home)",
    "Viper Manor Sewers - Entrance (Another)",
    "Viper Manor - Bridge to Treasure Tower",
    "Viper Manor - Treasure Tower",
    "SCENE - Belthasar explains dimensions",
    "Viper Manor Balcony Edge (Night)",
    "Viper Manor - Jail Cell",
    "Viper Manor - Throne Room (After Invasion)",
    "Viper Manor Foyer (Escape from Porre)",
    "Viper Manor Stables Courtyard (Escape from Porre)",
    "Viper Manor Basement Hall (During Break-In)",
    "Viper Manor Foyer (During Break-In)",
    "Viper Manor Treasury (maybe After Invasion)",
    "Viper Manor Gates (After Invasion)",
    "Viper Manor Courtyard (After Invasion)",
    "Viper Manor Study (After Invasion)",
    "Viper Manor Gates (Dario's Restoration) (Home)",
    "Viper Manor Courtyard (Dario's Restoration) (Home)",
    "Viper Manor - Viper's Room (After Invasion)",
    "Viper Manor - Neo Epoch",
    "Viper Manor - Executive Wing (Disabled Exits)",
    "Viper Manor Mess Hall (After Invasion)",
    "Guldove Dock (Home)",
    "Guldove Dock (Before Going with Macha) (Another)",
    "Guldove Shop Exterior (Home)",
    "Guldove Shop Exterior (Another)",
    "Guldove - Macha's Tent Upper Exterior (Home)",
    "Guldove - Macha's Tent Upper Exterior (Another)",
    "Guldove - Chief's Tent Exterior (Home)",
    "Guldove - Chief's Tent Exterior (Another)",
    "Guldove - Doc's House (Home)",
    "Guldove - Doc's House (Another)",
    "Guldove - Doc's Beds (Home)",
    "Guldove - Doc's Beds (Another)",
    "Guldove - Element Shop (Home)",
    "Guldove - Element Shop (Another)",
    "Guldove Bar (Home)",
    "Guldove Bar (Another)",
    "Guldove - Macha's Tent (Home)",
    "Guldove - Macha's Tent (Another)",
    "Guldove - Macha's Tent Lower Level (Home)",
    "Guldove - Macha's Tent Lower Level (Another)",
    "Guldove - Chief's Tent (Home)",
    "Guldove - Chief's Tent (Another)",
    "Guldove - Doc's House (After Lynx) (Another)",
    "Guldove - Doc's Beds (After Lynx) (Home)",
    "SCENE - Discussion with Kid and Korcha after escape from Lynx",
    "Guldove Dock (Another)",
    "SCENE - Orlha battles Porre soldiers",
    "Hydra Marshes Entrance (Home)",
    "Hydra Marshes Entrance (Another)",
    "Hydra Marshes Northeast of Entrance (Home)",
    "Hydra Marshes Northeast of Entrance (Another)",
    "Hydra Marshes Upper Area (Home)",
    "Hydra Marshes Upper Area (Another)",
    "Hydra Marshes Northwest of Entrance (Home)",
    "Hydra Marshes Northwest of Entrance (Another)",
    "Hydra Marshes - Branches (Home)",
    "Hydra Marshes - Branches (Another)",
    "Hydra Marshes - Beeba Pad (Home)",
    "Hydra Marshes - Beeba Pad (Another)",
    "Hydra Marshes - Wingapede Pad (Home)",
    "Hydra Marshes - Wingapede Pad (Another)",
    "Hydra Marshes - Hollow Tree (Home)",
    "Hydra Marshes - Hollow Tree (Another)",
    "Hydra Marshes - Quadffid Pool (Home)",
    "Hydra Marshes - Quadffid Pool (Another)",
    "Hydra Marshes - Hydra Pool (Home)",
    "Hydra Marshes - Hydra Pool (Another)",
    "El Nido (Home)",
    "El Nido (Another)",
    "El Nido Main Island (Home)",
    "El Nido Main Island (Another)",
    "Dead Sea",
    "Sea of Eden (Defense Activated)",
    "Divine Dragon Falls Cave (Home)",
    "Divine Dragon Falls Cave (Another)",
    "Sea of Eden (Home)",
    "Sea of Eden (Chronopolis Exposed) (Another)",
    "Divine Dragon Falls (Home)",
    "Divine Dragon Falls (Another)",
    "S.S. Invincible Deck",
    "S.S. Invincible First Level (During Ghost Siege)",
    "S.S. Invincible Second Level",
    "S.S. Invincible Hull (During Ghost Siege)",
    "S.S. Invincible Kitchen",
    "S.S. Invincible Storage (During Ghost Siege)",
    "S.S. Invincible Cannon Hold",
    "S.S. Invincible Hull",
    "S.S. Invincible Hammocks",
    "S.S. Invincible Special Deck SCENE - Fargo reminisces",
    "S.S. Invincible Deck (With Ghost Ship)",
    "S.S. Invincible First Level",
    "S.S. Invincible Mess Hall",
    "S.S. Invincible First Level Beds",
    "S.S. Invincible Second Level Beds",
    "S.S. Invincible Storage",
    "S.S. Invincible - Captain's Quarters",
    "Hermit's Hideaway (Home)",
    "Hermit's Hideaway (Another)",
    "Hermit's Hideaway Interior (Home)",
    "Hermit's Hideaway Interior (Another)",
    "Hermit's Hideaway Interior (Another)",
    "Hermit's Hideaway (Home)",
    "Water Dragon Isle (Home)",
    "Water Dragon Isle (Another)",
    "Water Dragon Isle Fairy Tree (Dwarf Attack) (Home)",
    "Water Dragon Isle Fairy Tree (Another)",
    "Water Dragon Isle Interior (Dwarf Attack) (Home)",
    "Water Dragon Isle Falls (Dwarf Attack) (Home)",
    "Water Dragon Isle Water Dragon (Home)",
    "Water Dragon Isle Fairy Tree (Home)",
    "Water Dragon Isle Interior (Home)",
    "Water Dragon Isle Falls (Home)",
    "Water Dragon Isle Campfire SCENE - Kid talks to Serge",
    "SCENE - The fairies criticize the humans at sundown",
    "Mt. Pyre (Home)",
    "Mt. Pyre (Another)",
    "Mt. Pyre Second Area (Home)",
    "Mt. Pyre Second Area (Another)",
    "Mt. Pyre Third Area (Home)",
    "Mt. Pyre Third Area (Another)",
    "Mt. Pyre Slide Falls (Home)",
    "Mt. Pyre Slide Falls (Another)",
    "Mt. Pyre Lower Passage (Home)",
    "Mt. Pyre Lower Passage (Another)",
    "Mt. Pyre Dragon (Home)",
    "Mt. Pyre Dragon (Another)",
    "Mt. Pyre Slide Falls (Frozen) (Home)",
    "Mt. Pyre Slide Falls (Frozen) (Another)",
    "Fort Dragonia (Home)",
    "Fort Dragonia (Another)",
    "Fort Dragonia Main Bridge (Home)",
    "Fort Dragonia Main Bridge (Another)",
    "Fort Dragonia West Bridge (Home)",
    "Fort Dragonia West Bridge (Another)",
    "Fort Dragonia Northwest Bridge (Home)",
    "Fort Dragonia Northwest Bridge (Another)",
    "Fort Dragonia Northeast Bridge (Home)",
    "Fort Dragonia Northeast Bridge (Another)",
    "Fort Dragonia East Bridge (Home)",
    "Fort Dragonia East Bridge (Another)",
    "Fort Dragonia Lobby (Home)",
    "Fort Dragonia Lobby (Another)",
    "Fort Dragonia Northeast (Home)",
    "Fort Dragonia Northeast (Another)",
    "Fort Dragonia Northeast Second Area (Home)",
    "Fort Dragonia Northeast Second Area (Another)",
    "Fort Dragonia Northeast Third Area (Home)",
    "Fort Dragonia Northeast Third Area (Another)",
    "Fort Dragonia Northeast Crystal (Home)",
    "Fort Dragonia Northeast Crystal (Another)",
    "Fort Dragonia Northwest Area (Home)",
    "Fort Dragonia Northwest Area (Another)",
    "Fort Dragonia Northwest Right Room (Home)",
    "Fort Dragonia Northwest Right Room (Another)",
    "Fort Dragonia Northwest Left Room (Home)",
    "Fort Dragonia Northwest Left Room (Another)",
    "Fort Dragonia Northwest Crystal (Home)",
    "Fort Dragonia Northwest Crystal (Another)",
    "Fort Dragonia West Maze (Home)",
    "Fort Dragonia West Maze (Another)",
    "Fort Dragonia Dragon Tear Chamber (SCENE - Crystal activations) (Home)",
    "Fort Dragonia Dragon Tear Chamber (SCENE - Crystal activations) (Another)",
    "S.S. Zelbess Special Deck (SCENE - Nikki tells Kid about the Magical Dreamers)",
    "Fort Dragonia Dragon Tear Chamber with Broken Statues (SCENE - Karsh, ZOAH, and Marcy find General Viper)",
    "Fort Dragonia West Arrangement Room (Home)",
    "Fort Dragonia West Arrangement Room (Another)",
    "Fort Dragonia East Area (Home)",
    "Fort Dragonia East Area (Another)",
    "Fort Dragonia East Area Selection (Home)",
    "Fort Dragonia East Area Selection (Another)",
    "Fort Dragonia East Area Crystal (Home)",
    "Fort Dragonia East Area Crystal (Another)",
    "Fort Dragonia Central Elevator (Home)",
    "Fort Dragonia Central Elevator (Another)",
    "Fort Dragonia - Second Story Elevator Lobby (Home)",
    "Fort Dragonia - Second Story Elevator Lobby (Another)",
    "Fort Dragonia - Second Story Teleporter Room (Home)",
    "Fort Dragonia - Second Story Teleporter Room (Another)",
    "Fort Dragonia - Second Story Side-Staircase (Home)",
    "Fort Dragonia - Second Story Side-Staircase (Another)",
    "Fort Dragonia - Second Story Crystal (Home)",
    "Fort Dragonia - Second Story Crystal (Another)",
    "Fort Dragonia - Dragon Tear Chamber Station (Home)",
    "Fort Dragonia - Dragon Tear Chamber Station (Another)",
    "Fort Dragonia - Dragon Tear Chamber (Home)",
    "Fort Dragonia - Dragon Tear Chamber (SCENE - Serge confronts Lynx and Viper) (Another)",
    "Fort Dragonia Basement (Home)",
    "Fort Dragonia Basement (Another)",
    "Temporal Vortex",
    "Temporal Vortex - Sprigg's House",
    "Temporal Vortex - Confusion Complex",
    "Temporal Vortex - Chaos",
    "S.S. Zelbess Deck",
    "S.S. Zelbess First Level",
    "S.S. Zelbess Second Level",
    "S.S. Zelbess Inn",
    "S.S. Zelbess Restaurant",
    "S.S. Zelbess Demi-human Room",
    "S.S. Zelbess Hold",
    "S.S. Zelbess Hull (SCENE (05) - Party walks to boat with Magical Dreamers theme)",
    "S.S. Zelbess Comedy Backstage",
    "Crash",
    "S.S. Zelbess - Captain's Quarters",
    "S.S. Zelbess - Casino",
    "S.S. Zelbess - Magical Dreamers Stage (SCENE - Magical Dreamers concert)",
    "S.S. Zelbess - Magical Dreamers Ship Deck",
    "S.S. Zelbess - Magical Dreamers Ship - Nikki's Room",
    "S.S. Zelbess - Magical Dreamers Ship - Miki's Room",
    "S.S. Zelbess - Grand Slam",
    "S.S. Zelbess - Deck (After Marbule Failure)",
    "S.S. Zelbess - Hull (SCENE (05) - Demi-humans begin to row)",
    "SCENE - Magical Dreamers stage opens up to S.S. Zelbess",
    "S.S. Zelbess Inn Attic (SCENE - Demi-human manipulates Casino)",
    "Marbule (Before Restoration) (Home)",
    "Marbule (Another)",
    "Marbule - Black Dragon Cave (Home)",
    "Marbule - Black Dragon Cave (Another)",
    "Marbule - Chief's Cave (Home)",
    "Marbule - Chief's Cave (Another)",
    "Marbule - Witch Doctor's Cave (Home)",
    "Marbule - Witch Doctor's Cave (Another)",
    "Marbule - Bro. of G's Shop (Home)",
    "Marbule - Bro. of G's Shop (Disabled Exits)",
    "Marbule - Mermaid Pirate House (Home)",
    "Marbule - Mermaid Pirate House (Disabled Exits)",
    "Marbule - Child Demi-human's Cave",
    "Marbule (After Restoration) (Home)",
    "Death's Door",
    "Pearly Gates",
    "Earth Dragon Isle (Home)",
    "Earth Dragon Isle (Another)",
    "Earth Dragon Isle Underground (Home)",
    "Earth Dragon Isle Underground (Another)",
    "Earth Dragon Isle Sand Boil (Home)",
    "Earth Dragon Isle Sand Boil (Another)",
    "Earth Dragon Isle - Earth Dragon (Home)",
    "Earth Dragon Isle - Criosphinx (Another)",
    "Isle of the Damned (Home)",
    "Isle of the Damned (Another)",
    "Isle of the Damned Dragon Bones (Home)",
    "Isle of the Damned Dragon Bones (Another)",
    "Isle of the Damned WightKnight (Home)",
    "Isle of the Damned WightKnight (Another)",
    "Isle of the Damned Grave (Home)",
    "Isle of the Damned Grave (Another)",
    "SCENE - Karsh battles the corrupted Dario",
    "Crash (Forbidden Island (Home) (maybe))",
    "Forbidden Island Cabin (Home)",
    "Forbidden Island (Another)",
    "Forbidden Island Cabin (Another)",
    "Sky Dragon Isle (Home)",
    "Sky Dragon Isle (Another)",
    "Sky Dragon Isle Stairway (Home)",
    "Sky Dragon Isle Stairway (Another)",
    "Sky Dragon Isle Summit (Home)",
    "Sky Dragon Isle Summit (Another)",
    //------------------------------------------------ CD2 diff stats here ------------------------------------------------//
    "Terra Tower", // 439
    "Terra Tower - Stairway", // 440
    "Terra Tower - Summit",
    "Terra Tower - Frozen flame closeup", // 442
    "El Nido Triangle (Home)",
    "El Nido Triangle (Another)",
    "El Nido Triangle - First Area (Home)",
    "El Nido Triangle - First Area (Another)", // 446
    "El Nido Triangle - Second Area (Home)",
    "El Nido Triangle - Second Area (Another)",
    "El Nido Triangle - Inside Sparky ship",
    "Gaea's Navel (Home)", // 450
    "Gaea's Navel (After Beating Monsters) (Home)",
    "Gaea's Navel Right from Entrance (Home)",
    "Gaea's Navel Right from Entrance (Another)",
    "Gaea's Navel Right from Last (Home)",
    "Gaea's Navel Right from Last (Another)",
    "Gaea's Navel Green Dragon (Home)",
    "Gaea's Navel Green Dragon (Another)",
    "", // 458
    "SCENE - Dragon god arrive at the top of dragon island", // 459
    "SCENE - Harle put flowers on Serge grave",
    "SCENE - Arni inhabited by demi-humans",
    "Programmers Room - Main 1", // 462
    "Programmers Room - Far Left Of Main 1",
    "Programmers Room - Left Of Main 1",
    "Programmers Room - Right Of Main 1",
    "Programmers Room - Far Right Of Main 1",
    "Programmers Room - Main 2",
    "Programmers Room - Far Left Of Main 2",
    "Programmers Room - Left Of Main 2",
    "Programmers Room - Right Of Main 2", // 470
    "Programmers Room - Far Right Of Main 2",
    "",
    "", // 473
    "Fate Present Isle",
    "Fate Future Isle",
    "Fate Past Isle",
    "Chronopolis - Lobby",
    "Chronopolis - Sewer", // 478
    "Chronopolis",
    "Chronopolis", // 480
    "Chronopolis - Black hole room",
    "Chronopolis - Brain room",
    "Chronopolis",
    "Chronopolis - Home and Another observation room",
    "Chronopolis", // 485
    "Chronopolis - Map",
    "Chronopolis - 2F",
    "Chronopolis",
    "Chronopolis - Docks",
    "Chronopolis - Frozen flame room door", // 490
    "Chronopolis - Frozen flame room",
    "Chronopolis - SCENE Frozen flame room",
    "Chronopolis",
    "Chronopolis - 3F",
    "Chronopolis - 4F",
    "Burning Orphange - 1", // 496
    "Burning Orphange - 2",
    "Burning Orphange - 3",
    "Burning Orphange - 4",
    "Burning Orphange - 5",
    "Burning Orphange - 6",
    "Burning Orphange - 7",
    "Burning Orphange - 8",
    "Burning Orphange - SCENE Kid saved",
    "Terra Tower - Dock", // 505
    "Terra Tower",
    "Terra Tower",
    "Terra Tower",
    "Terra Tower",
    "Terra Tower", // 510
    "Terra Tower",
    "Terra Tower",
    "Terra Tower",
    "Terra Tower",
    "Terra Tower", // 515
    "Terra Tower",
    "Terra Tower",
    "Terra Tower",
    "Terra Tower - Elevator going up",
    "Terra Tower", // 520
    "Terra Tower",
    "Terra Tower",
    "Terra Tower",
    "Terra Tower",
    "Terra Tower",
    "Terra Tower",
    "Terra Tower", // 527
    "Viper manor - Bridge",
    "Viper manor - Library with CC ghosts",
    "Boat in from on Terra Tower", // 530
    "Bend of time - 1",
    "Bend of time - 2",
    "Chrono Cross logo",
    "Earth - ending",
    "Screen - Terra tower attacked", // 535
    "Screen - Lavos",
    "Screen - Terra tower",
};

const char* getRoomName(int discIdx, int roomIdx)
{
    if(discIdx == 0)
    {
        if((roomIdx >= 0) && (roomIdx < (sizeof(CCRoomName_CD1)/sizeof(const char*))))
        {
            return CCRoomName_CD1[roomIdx];
        }
    }
    if(discIdx == 1)
    {
        if((roomIdx >= 0) && (roomIdx < (sizeof(CCRoomName_CD2)/sizeof(const char*))))
        {
            return CCRoomName_CD2[roomIdx];
        }
    }
    return NULL;
}