
void FFVII_System_RenderPacketChangeTransparency(); // system_change_semi_transparency_in_packet
void FFVII_System_RenderPacketChangeBrightness(); // system_change_brightness_calculation_in_packet
void FFVII_System_RenderPacketCreateCLUT(); // system_create_clut_for_packet
void FFVII_System_RenderPacketCreateTextureSettings(); // system_create_texture_page_settings_for_packet
void FFVII_System_RenderPacketAddToQueue(); // system_add_render_packet_to_queue
void FFVII_System_RenderDrawEnviromentCreateStruct(); // system_graphic_create_draw_env_struct
void FFVII_System_RenderDrawEnviromentCreatePackets(); // system_prepare_draw_env_packets
